name: Android-Go-CI
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '05 * * * *'
jobs:
  Check:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 359
    strategy:   
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'         
    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*.jar
        tag: jar
        file_glob: true
        overwrite: true
        release_name: jar      
    - name: Update
      run: |
        rm README.md
        date >> README.md         
        python generate.py        
    - name: Commit  ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -am "Update File"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git    
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 1  
  build:
    needs: Check
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    env:
        NUM_JOBS: 40
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
  deploy:
    needs: build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    env:
        NUM_JOBS: 180
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: Vampire/setup-wsl@v1
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
    - name: Start
      continue-on-error: true
      run: java -jar apk.jar
